spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/selfcare
          jwk-set-uri:  ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 9092
logging:
  level:
    org.springframework.security : DEBUG

jwt:
  auth:
    converter:
      resource-id: bff
      principal-attribute: preferred_username
